# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/

title: Andreas Holm Nielsen
description: PhD Student in Machine Learning at Aarhus University. My research area involves Machine Learning applied to the Atmospheric Sciences such as Weather Forecasting using Geostationary Satellite Images.
github_username: holmdk

# Email and twitter are optional:
email: 
twitter_username: HolmML
linkedin_username: andreas-holm-nielsen-13128161/

# Set this to true to get LaTeX math equation support
use_math: true

# Everything below here can be ignored, unless you want to change the theme entirely
theme: minima
plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-octicons

titles_from_headings:
  enabled:     true
  strip_title: true
  collections: true

highlighter: rouge
markdown: kramdown
kramdown:
  math_engine: katex
  input: GFM
  auto_ids: true
  hard_wrap: false
  syntax_highlighter: rouge
